file_format: "1"
id: avalanche
name: Avalanche V4
type: shield
url: https://github.com/vlkv/avalanche
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - avalanche_v4_left
